# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b340392956ef30f88e8e3144aa9686283c125c189d888d3d1a143b1aa25abac673a24de24e931cfb229c73bdce31062fec0ee5e3bb648b510b70456c577aa39e

test:
  secret_key_base: ba254361c7517e3aa47e48c19ba18d4aff6d7428708eebf48680c823a2a873254422bfcf212bef443b874f001e8be5cadf40619e640a365f1e109bd1206fca8d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
